import type { ChecklistPhase, PrestaType } from '@/types/project-v2'

export type TemplateTask = { phase: ChecklistPhase; title: string }

// Template ERP V3 partagé entre `erp_v2` (clé canonique) et `erp` (legacy).
// Toute modification du process ERP se fait ici, propagation automatique.
const ERP_V3_TASKS: TemplateTask[] = [
  { phase: 'onboarding',     title: 'Réunion de cadrage + immersion métier' },
  { phase: 'onboarding',     title: 'Audit des processus existants (outils, points de douleur, volumétrie)' },
  { phase: 'onboarding',     title: 'Rédaction CDC fonctionnel + PRD + ACTION_PLAN' },
  { phase: 'onboarding',     title: 'Validation CDC client + signature' },
  { phase: 'conception',     title: 'Architecture technique (Next.js + Supabase + Edge Functions, infra Propul\'SEO)' },
  { phase: 'conception',     title: 'Modélisation base de données + schéma RLS multi-tenant' },
  { phase: 'conception',     title: 'Maquettes UX des écrans clés (dashboard, kanban, formulaires)' },
  { phase: 'conception',     title: 'Validation parcours & design client' },
  { phase: 'developpement',  title: 'Setup environnements (dev / staging / prod) + pipeline Coolify' },
  { phase: 'developpement',  title: 'Migrations SQL + seed data réaliste' },
  { phase: 'developpement',  title: 'Authentification + rôles + permissions (JWT enrichi tenant_id)' },
  { phase: 'developpement',  title: 'Modules métier (CRUD, workflows, scoring, OCR, génération PDF)' },
  { phase: 'developpement',  title: 'Intégrations API & Edge Functions (Stripe, IA Claude, webhooks, cron)' },
  { phase: 'recette',        title: 'Tests E2E flux critiques + recette fonctionnelle avec client' },
  { phase: 'recette',        title: 'Recette signée client' },
  { phase: 'post_livraison', title: 'Go-live (Coolify + DNS + SSL + monitoring) + formation équipes' },
  { phase: 'post_livraison', title: 'Support post-déploiement J+30 (hotfix, ajustements, documentation)' },
]

export const TEMPLATES: Record<PrestaType, TemplateTask[]> = {
  site_web: [
    { phase: 'onboarding',     title: 'Réunion de lancement + immersion métier' },
    { phase: 'onboarding',     title: 'Audit de l\'existant (site, SEO, contenu, analytics, process)' },
    { phase: 'onboarding',     title: 'Collecte des accès (domaine, Supabase, Stripe, CMS, GA/GSC)' },
    { phase: 'onboarding',     title: 'Rédaction & validation du brief / PRD' },
    { phase: 'conception',     title: 'Arborescence, wireframes & parcours utilisateurs' },
    { phase: 'conception',     title: 'Maquettes graphiques + brand book / design system' },
    { phase: 'conception',     title: 'Validation design client + plan de retours' },
    { phase: 'conception',     title: 'Récupération & préparation contenus (textes, photos, scrape réseaux)' },
    { phase: 'developpement',  title: 'Setup projet Next.js (Tailwind + shadcn/ui, infra Propul\'SEO)' },
    { phase: 'developpement',  title: 'Schéma Supabase + RLS + migrations SQL' },
    { phase: 'developpement',  title: 'Intégration design responsive (sections, composants UI)' },
    { phase: 'developpement',  title: 'Modules métier (questionnaire, panier, formulaires, portail client)' },
    { phase: 'developpement',  title: 'Intégrations tierces (Stripe, Resend/Brevo, BAN, Pappers, Mondial Relay)' },
    { phase: 'recette',        title: 'SEO technique (meta, sitemap, schema.org, redirections 301, Lighthouse)' },
    { phase: 'recette',        title: 'Tests E2E flux critiques (paiement, formulaires, parcours conversion)' },
    { phase: 'recette',        title: 'Corrections retours client (cycles itératifs)' },
    { phase: 'post_livraison', title: 'Déploiement Coolify + DNS + SSL + RGPD/cookies + monitoring' },
    { phase: 'post_livraison', title: 'Formation client + documentation + demande d\'avis Google' },
  ],
  erp_v2: ERP_V3_TASKS,
  communication: [
    { phase: 'onboarding',     title: 'Brief mensuel reçu' },
    { phase: 'conception',     title: 'Calendrier éditorial validé' },
    { phase: 'developpement',  title: 'Visuels créés' },
    { phase: 'developpement',  title: 'Textes rédigés' },
    { phase: 'recette',        title: 'Validation client' },
    { phase: 'post_livraison', title: 'Programmation des posts' },
    { phase: 'post_livraison', title: 'Rapport de performance envoyé' },
  ],
  // ===== LEGACY (rétrocompatibilité projets V1/V2 existants en BDD) =====
  web: [
    { phase: 'onboarding',     title: 'Réunion de lancement' },
    { phase: 'onboarding',     title: 'Collecte des accès' },
    { phase: 'onboarding',     title: 'Validation du brief' },
    { phase: 'conception',     title: 'Maquettes wireframes' },
    { phase: 'conception',     title: 'Maquettes graphiques' },
    { phase: 'conception',     title: 'Validation design client' },
    { phase: 'developpement',  title: 'Intégration HTML/CSS' },
    { phase: 'developpement',  title: 'Développement fonctionnalités' },
    { phase: 'developpement',  title: 'Mise en place CMS' },
    { phase: 'developpement',  title: 'Tests internes' },
    { phase: 'recette',        title: 'Tests utilisateurs' },
    { phase: 'recette',        title: 'Corrections retours client' },
    { phase: 'recette',        title: 'Validation finale' },
    { phase: 'post_livraison', title: 'Mise en ligne' },
    { phase: 'post_livraison', title: 'Formation client' },
    { phase: 'post_livraison', title: 'Garantie 30j' },
  ],
  seo: [
    { phase: 'onboarding',     title: 'Audit technique SEO' },
    { phase: 'onboarding',     title: 'Accès GA/GSC/Search Console' },
    { phase: 'onboarding',     title: 'Réunion stratégie' },
    { phase: 'conception',     title: 'Analyse mots-clés' },
    { phase: 'conception',     title: 'Stratégie de contenu' },
    { phase: 'conception',     title: 'Audit concurrentiel' },
    { phase: 'developpement',  title: 'Optimisations on-page' },
    { phase: 'developpement',  title: 'Création/optimisation contenu' },
    { phase: 'developpement',  title: 'Stratégie netlinking' },
    { phase: 'recette',        title: 'Rapport de performance' },
    { phase: 'recette',        title: 'Validation objectifs KPI' },
    { phase: 'post_livraison', title: 'Suivi mensuel KPIs' },
    { phase: 'post_livraison', title: 'Rapport final' },
  ],
  // Alias V3 : `erp` (legacy) utilise désormais le même template que `erp_v2`.
  // Rétrocompat des projets BDD qui ont `presta_type=['erp']`.
  erp: ERP_V3_TASKS,
  saas: [
    { phase: 'onboarding',     title: 'Discovery & product roadmap' },
    { phase: 'onboarding',     title: 'Architecture technique' },
    { phase: 'onboarding',     title: 'Setup environnements' },
    { phase: 'conception',     title: 'Maquettes UI/UX' },
    { phase: 'conception',     title: 'Spécifications fonctionnelles' },
    { phase: 'developpement',  title: 'MVP développement' },
    { phase: 'developpement',  title: 'Tests automatisés' },
    { phase: 'developpement',  title: 'CI/CD pipeline' },
    { phase: 'recette',        title: 'Beta testing' },
    { phase: 'recette',        title: 'Corrections et optimisations' },
    { phase: 'post_livraison', title: 'Lancement production' },
    { phase: 'post_livraison', title: 'Monitoring & analytics' },
  ],
}
